<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '-- Select --' => '',
    'Add Weight' => '',
    'Are you sure you want to delete this item?' => '',
    'Articles' => '',
    'Articles Categories' => '',
    'Attribute ID' => '',
    'Cms Pages' => '',
    'Congratulations!' => '',
    'Date' => '',
    'Date Create' => '',
    'Date Update' => '',
    'Default' => '',
    'Delete' => '',
    'ID' => '',
    'Local' => '',
    'Login' => '',
    'Logout ({name})' => '',
    'Member ID' => '',
    'More...' => '',
    'My Current Weight: {weight} lbs' => '',
    'My Page' => '',
    'My Starting Weight: {weight} lbs' => '',
    'My Tools' => '',
    'My Weight Entries' => '',
    'Name' => '',
    'No results found.' => '',
    'Option ID' => '',
    'Page not found.' => '',
    'Please answer the question: "{question}"' => '',
    'Please complete payment before access' => '',
    'Price per month' => '',
    'Profile' => '',
    'Question ID' => '',
    'Recipes' => '',
    'Recipes Categories' => '',
    'Save' => '',
    'Showing {begin}-{end} of {count} item(s).' => '',
    'Signup' => '',
    'Update' => '',
    'Url' => '',
    'Value' => '',
    'Weight' => '',
    'Weight Tracker' => '',
];
