<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '-- Select --' => '-- Velg --',
    'Add Weight' => 'Legg til vekt',
    'Are you sure you want to delete this item?' => 'Er du sikker på at du vil slette dette?',
    'Articles' => 'Sider',
    'Articles Categories' => 'Innlegg',
    'Attribute ID' => 'ID for egeneskaper',
    'Cms Pages' => 'Cms sider',
    'Date' => 'Dato',
    'Date Create' => 'Legg til dato',
    'Date Update' => 'Oppdater dato',
    'Default' => 'Standard',
    'Delete' => 'Slett',
    'ID' => 'ID',
    'Local' => 'Lokal',
    'Login' => 'Logg inn',
    'Logout ({name})' => 'Logg ut ({name})',
    'Member ID' => 'Medlems ID',
    'More...' => 'Mer...',
    'My Current Weight: {weight} lbs' => 'Min nåværende vekt: {weight} i lb',
    'My Page' => 'Min Side',
    'My Starting Weight: {weight} lbs' => 'Min startvekt {weight} i lb',
    'My Tools' => 'Mine verktøy',
    'My Weight Entries' => 'Min vekttabell',
    'Name' => 'Navn',
    'No results found.' => 'Ingen resultater funnet.',
    'Option ID' => 'Valg ID',
    'Page not found.' => 'Side ikke funnet.',
    'Please answer the question: "{question}"' => 'Alle spørsmål må besvares: "{question}"',
    'Please complete payment before access' => 'Fullfør betalingen for å få tilgang til siden din',
    'Price per month' => 'Pris pr måned',
    'Profile' => 'Profil',
    'Question ID' => 'Spørsmåls ID',
    'Recipes' => 'Oppskrifter',
    'Recipes Categories' => 'Oppskrifter',
    'Save' => 'Lagre',
    'Showing {begin}-{end} of {count} item(s).' => 'Viser {begin}-{end} av {count} elementer.',
    'Signup' => 'Registrer deg',
    'Today' => '',
    'Update' => 'Oppdater',
    'Url' => '',
    'Value' => 'Verdi',
    'Weight' => 'Vekt',
    'Weight Tracker' => 'Vekttabell',
];
